### ISSUE TITLE
github 与 博客

### ISSUE THREAD

**Issue by imsobear** [imsobear/blog#27]
![风景](https://f.cloud.github.com/assets/2505411/1276949/97050884-2ea0-11e3-89cf-0bcdfd8cf225.jpg)

如今用github写博客的人越来越多，尤其是在程序员的圈子里，对我个人来讲，这的确是个很便利的东西，下面就介绍一下用github写博客主要的两种方式：
#### 1. jeklly/octopress + github pages：

这种方式是最常见的，我也试过一段时间，虽然说用 markdown 听起来逼格很高的样子，但是每次要在本地 `rake deploy` 实在是不爽，而且刚开始配置的时候还很麻烦，所以我很早就明智的放弃了这种方式。
#### 2. issues （+ github pages）：

在issues里写博客的鼻祖是谁我不了解，我只知道「玉伯」用的比较早，然后下面的评论也很有料，而我现在也是用这种方式，说一下有哪些特点：
- 编辑简单快速：这是最重要的了，随时可以新开issue写博客，也可以即时修改，方便轻巧；
- 添加图片方便：新开一个issue后下面会有一个`插入图片`的功能，添加图片很方便；
- 体验很好：无论是编辑文章、阅读文章或者评论功能，用起来体验都比较爽，谁用谁知道；
- 数据安全：记得之前用wordpress托管在一个国外的免费服务商那里，博客被无缘封了我就不说了，数据差点没导出来，虽然说咱也没写出什么有料的东西；
- 不用备份，速度也不错：访问速度不会受其他因素影响，也不存在被挡在墙外的情况。

有优点当然也有缺点：
- 过于小众：只有程序员才用这个，不过程序员的圈子也就是程序员了，这点事也不算事；
- 订阅问题：RSS订阅是不靠谱了，可以选择watch一下项目，不过要是博主哪天抽风，你的timeline会被刷爆的，据说我的朋友有一次收到 github 50多封邮件，因为那天我重新整理了issue列表，然后就被取消关注了～
- 自动保存：github在线编辑不提供自动保存，这一点还是让我很胆战心惊的，不过胆子是练粗来的。

还有一些tips分享一下：

**1. 标签：** github issues里本身就有这个功能，你可以很方便的管理文章标签，而且还有不同的颜色标注；

**2. 个人域名：**这个就要结合github pages来用了，可以参考[github page](https://help.github.com/categories/20/articles)。

我目前设置的是[sobear.me](http://sobear.me)跳转到我的首页，然后[sobear.me/blog](http://sobear.me/blog)跳转到issues列表，前者参看文档很容易实现，后者主要的方法是在`gh-pages`里新建一个目录`blog`，然后里面有一个文件`index.html`，在html里实现跳转到issues列表，两种跳转方式：

``` javascript
location.href = "https://github.com/tomayday/MyBlog/issues?state=open";
```

或者

``` html
<meta http-equiv="refresh" content="0;url=https://github.com/tomayday/MyBlog/issues?state=open">
```

然后输入sobear.me/blog就会直接跳转到issue列表里面。

github写博客的用法差不多就这些，也听说有人用gist，但个人感觉不太爽。然后github其实还有一些有趣的用法，比如前不久有人[用github发婚礼请柬](http://www.36kr.com/p/205932.html)，然后今天小伙伴说用github还可以表白，比如去某女神的某项目里`open issue`，然后blablabla，I Love U~~~
# 

说好的台风没见动静，这让我感到绝望，Miss Dong !

题图来自[tumblr](http://catalonso.tumblr.com/post/61960099953)

--OVER--

**Comment by pynixwang** [comment]
为什么这个会给我发通知？
