### ISSUE TITLE
JavaScript 阻止页面关闭

### ISSUE THREAD

**Issue by imsobear** [imsobear/blog#28]
场景：经常会看到一些需要编辑的页面，在关闭页面时会触发一个弹窗的事件，询问用户是否确定关闭，这个事件就是今天要说的`beforeunload`。

在 jQuery 中提供了一个叫`unload`的事件，号称这样用：

``` javascript
$(window).unload(function() {
     return '确定要关闭？';
});
```

但实际上经测试这玩意不靠谱啊，不信你试试，社区没人吐槽这事吗....后来发现jQuery提供的事件叫`beforeunload`，奇怪的是在jQuery的官网里是搜不到这个API，但是能搜到`unload`...jQuery封装的这个方法跟原生的JS实现其实差不多，甚至说原生的JS更好用一些，jQuery中是这样定义的：

``` javascript
beforeunload: {
      postDispatch: function( event ) {

      // Support: Firefox 20+
      // Firefox doesn't alert if the returnValue field is not set.
      if ( event.result !== undefined ) {
            event.originalEvent.returnValue = event.result;
       }
    }
}

// 使用 beforeunload
$(window).bind('beforeunload', function() {
      return 1;
})
```

实际上在原生的JS中使用这个事件是非常简单的：

``` javascript
window.addEventListener('beforeunload', function (e) {
       return '您正在编辑的 issue 还没有提交，确定要离开？';
});
```

事实上我本来想实现的功能是关闭页面时弹出自己自定义的浮层，样式都写好了：
![1](https://f.cloud.github.com/assets/2505411/1320274/1a8f0674-3350-11e3-8ae4-ff9e866a4d6e.JPG)
然后我想的方式，是触发这个事件时，阻止事件的默认行为（不显示默认的系统框，但不关闭页面），显示自定义的框，然后点击「确认离开」后关闭页面。理想是丰满的，现实是残酷的。遇到的问题：
1. 无法实现关闭页面时不显示默认的系统框，目前无解，后面的工作无法进行，所以如果见过哪个网站的这种框是自定义的，求通知一下... 
   PS：开发者无法自定义这个默认框的样式。
2. 点击「确认离开」时不再重复触发这个事件。刚才想的方案是定义一个参数，通过判断参数值确认是否触发`beforeunload`事件：

``` javascript
var close = doc.querySelector('.close'),
     isSure = false;

$(window).bind('beforeunload', function(e) {
    if (!isSure) {
        return '确认关闭？';
    }
})

close.addEventListener('click', function() {
    isSure = true;
})
```

但是现在第一个问题解决不了，后面想的就是扯淡...如果有什么思路，还望指明哈～

**Comment by barretlee** [comment]
Google 找到果大的文章了；）

**Comment by imsobear** [comment]
@barretlee 吓得我赶紧把 repo 删除了 =。=

**Comment by sumaolin** [comment]
嗯，也遇到相似的情况，页面关闭时候想发送个http request，经常失败！
