### ISSUE TITLE
JavaScript 实现复制内容到剪贴板

### ISSUE THREAD

**Issue by imsobear** [imsobear/blog#31]
这个问题算是之前项目的一个遗留问题，前不久研究总结了一下，记录在这里。
### 问题：

如何用 js 实现点击一段文本时将文本复制到剪贴板上？
#### 1. Flash 实现：

目前有这个需求的网站基本都是这个解决方案，比如说`github`的这个功能：
![copy](https://f.cloud.github.com/assets/2505411/1458829/4a6e48e4-439c-11e3-9043-84bf295edb89.JPG)

我们今天主要说js的实现，所以flash的实现方式就不做介绍了。
#### 2. js 实现：

很遗憾，因为安全方面的考虑，除IE以外的其他浏览器的都不允许js去做这件事，既然不能直接实现，我们只能考虑一下退化方案，我个人的退化方案是：鼠标移到目标文字时，文字被选中，然后提示用户按下 `ctrl+c` 可以复制。

OK，按照以上的需求，我们需要解决的问题：
- **如何让文字处于选中状态？**

jQuery 提供了一个现成的方法`select()`，你只需要这样做 `elem.select()` 就可以搞定。

用原生js实现，需要针对不同浏览器做一些兼容性的处理：

``` javascript
function selectText (element) {
    var text = element,
        range,
        selection;

    if (body.createTextRange) {
        // IE
        range = body.createTextRange();
        range.moveToElementText(text);
        range.select();
    } else if (window.getSelection) {
        // Others
        selection = window.getSelection();
        range = doc.createRange();
        range.selectNodeContents(text);
        selection.removeAllRanges();
        selection.addRange(range);
    } else {
        return false;
    }
}
```

然后你只需要对相应的元素绑定 `mouseenter` 的事件，然后响应 `selectText()` 这个方法就 ok。

可以参考stackoverflow的[这个问题](http://stackoverflow.com/a/987376/1189321)。
- **怎么设置选中状态的样式？**（可选）

浏览器中文字在选中状态下本身就会有默认的状态，没错，就是那蓝色的一坨，在IE下目前所了解的是不可以自定义这个样式的，但在 chrome 和 firefox 下可以自定义：

``` css
/* 选中后的文字样式 */
::selection {
    color: #fff;
    background-color: #1abc9c;
}
::-moz-selection {
    color: #fff;
    background-color: #1abc9c;
}
```

然后就可以看到这样的效果了：

![](https://github-camo.global.ssl.fastly.net/afcc2264de1f652fc9b4965e46a08dd1da3cb86b/687474703a2f2f626c6f672d696d616765732e752e71696e6975646e2e636f6d2f636f70792e706e67)
### 3. 一点成果：

核心方法就是上文所提及的`selectText()`，然后一时兴起就把这个东西封装了一下， 还起了一个比较装逼的名字[copy.js](https://github.com/tomayday/copy.js)，[demo](http://tomayday.github.io/copy.js/)。

在封装的过程中，我想在上面的基础上，实现用户按下`ctrl+c`时再给一个「复制成功」的提示，然后碰到了如何监听用户同时按下 `ctrl+c` 的问题。

在 `event` 对象中本身就有`altKey`、`ctrlKey`这样的标志，所以只需要这样做：

``` javascript
document.addEventListener('keydown', function (e) {
    if (e.ctrlKey && e.keyCode === 67) {
        // 按下 ctrl + c
    }
});
```

--正文完--

在写copy.js时，需要写兼容IE8-的 `getElementsByClassName()` 的方法，一个老掉牙的笔试题，再次有了一点新的认识，之后会整理一下，留作下次分享。

**Comment by iblh** [comment]
Mark

**Comment by lovecn** [comment]
mark ps:clipboardjs

**Comment by silentsiri** [comment]
想问下现在这个需求有新的方案了吗？
