### ISSUE TITLE
浅析 NodeJs 的几种文件路径

### ISSUE THREAD

**Issue by imsobear** [imsobear/blog#48]
### 一、挖坑 & 掉坑：

缘起一段这样的代码：

``` node
fs.readFile('./docs/use.md', function (err, buffer) {
    if (err) {
      return console.log('error: ', err);
    }

    console.log('OK');
  });
```

本地运行时一切 OK，线上部署时却死活找不到 `./docs/use.md` 这个文件，后来才发现是因为线上启动应用时不是从当前目录启动了，不过为什么启动脚本的位置也会影响这个路径呢，且往下看。
### 二、填坑：

Node 中的文件路径大概有 `__dirname`, `__filename`, `process.cwd()`, `./` 或者 `../`，前三个都是绝对路径，为了便于比较，`./` 和 `../` 我们通过 `path.resolve('./')`来转换为绝对路径。

先看一个简单的栗子：

假如我们有这样的文件结构：

``` shell
app/
    -lib/
        -common.js
    -model
        -task.js
        -test.js
```

在 task.js 里编写如下的代码：

``` node
var path = require('path');

console.log(__dirname);
console.log(__filename);
console.log(process.cwd());
console.log(path.resolve('./'));
```

在 `model` 目录下运行 `node task.js` 得到的输出是：

```
/Users/guo/Sites/learn/app/model.js
/Users/guo/Sites/learn/app/model.js/task.js
/Users/guo/Sites/learn/app/model.js
/Users/guo/Sites/learn/app/model.js
```

然后在 `app` 目录下运行 `node model/task.js`，得到的输出是：

```
/Users/guo/Sites/learn/app/model.js
/Users/guo/Sites/learn/app/model.js/task.js
/Users/guo/Sites/learn/app
/Users/guo/Sites/learn/app
```

那么，不好意思不是问题来了~T_T,我们可以得出一些**肤浅的结论**了：
- __dirname: 总是返回被执行的 js 所在文件夹的绝对路径
- __filename: 总是返回被执行的 js 的绝对路径
- process.cwd(): 总是返回运行 node 命令时所在的文件夹的绝对路径
- ./: 跟 process.cwd() 一样、一样、一样的吗？

我明明记得在 `require('../lib/common')` 里一直都是各种相对路径写，也没见报什么错啊，我们还在再来个栗子吧，还是上面的结构，'model/task.js' 里的代码改成：

``` node
var fs = require('fs');
var common = require('../lib/common');

fs.readFile('../lib/common.js', function (err, data) {
    if (err) return console.log(err);
    console.log(data);
});
```

在 model 目录下运行 `node task.js`，一切 Ok，没有报错。然后在 app 目录下运行 `node model/task.js`，然后很果断滴报错了:

![](http://gtms02.alicdn.com/tps/i2/TB1cDSuGFXXXXaPXVXXub0fYFXX-563-81.png)

那么这下问题真的都是来了，按照上面的理论，在 app 下运行时，`../lib/common.js` 会被转成 `/Users/guo/Sites/learn/lib/common.js`，这个路径显然是不存在的，但是从运行结果可以看出 `require('../lib/common')` 是 OK 的，只是 readFile 时报错了。

那么关于 `./` 正确的结论是：

在 `require()` 中使用是跟 `__dirname` 的效果相同，不会因为启动脚本的目录不一样而改变，在其他情况下跟 `process.cwd()` 效果相同，是相对于启动脚本所在目录的路径。
### 三、总结：

只有在 `require()` 时才使用相对路径(./, ../) 的写法，其他地方一律使用绝对路径，如下：

```
// 当前目录下
path.dirname(__filename) + '/test.js';
// 相邻目录下
path.resolve(__dirname, '../lib/common.js');
```
### 四、参考链接：
- [What is the difference between __dirname and ./ in node.js](http://stackoverflow.com/questions/8131344/what-is-the-difference-between-dirname-and-in-node-js)
- [nodejs API](http://nodejs.org/api/)

以上:smile:。

**Comment by chaosforfun** [comment]
好吧，感谢填坑。

**Comment by ChangMM** [comment]
赞

**Comment by bhtbed** [comment]
其实原因很简单，require的路径必须是相对于当前执行文件的，否则你引用的node_module，它的require路径肯定不能够正确识别了呀。

**Comment by Pines-Cheng** [comment]
感谢填坑！

**Comment by gluu1** [comment]
有些地方的路径楼主写错了，请更正一下

**Comment by lamda-lin** [comment]
感谢躺坑

**Comment by feihe08** [comment]
写node的新人，这两天遇到了路径问题，多谢。

**Comment by gb-6k-house** [comment]
此坑早已踩！！！

**Comment by heysdc** [comment]
在坑里站了一晚上，刚找到原因顺藤摸瓜看到了这篇分析，我泪流满面

**Comment by sunWhereCode** [comment]
好文，谢谢博主

**Comment by ghost** [comment]
赞。

**Comment by tigerLVU** [comment]
好

**Comment by tonylouh** [comment]
👍

**Comment by Gringe920** [comment]
呜呜菜鸟表示看不大懂

**Comment by Akiq2016** [comment]
thank you!

**Comment by sirormy** [comment]
文件结构是不是model应该改成model.js啊, 跟输出的文件路径不匹配呢

**Comment by hacke2** [comment]
对于文件地址的凭借最好使用`path.join`，可以屏蔽各个操作系统之前的差异

**Comment by JoeeeeeWu** [comment]
model写成model.js了你...

**Comment by jiapeiyang** [comment]
感谢填坑！

**Comment by Mr0Lz** [comment]
谢谢

**Comment by sevencai** [comment]
/Users/guo/Sites/learn/app/model.js
/Users/guo/Sites/learn/app/model.js/task.js

=》应该是

/Users/guo/Sites/learn/app/model
/Users/guo/Sites/learn/app/model/task.js

**Comment by Hellowor1d** [comment]
一个很有营养的坑 :)

**Comment by kokokele** [comment]
只有在 require() 时才使用相对路径(./, ../) 的写法，其他地方一律使用绝对路径，如下：

// 当前目录下
path.dirname(__filename) + '/test.js';
// 相邻目录下
path.resolve(__dirname, '../lib/common.js');


---------------

应该是：
// 当前目录下
path.dirname(__dirname) + '/test.js';

**Comment by WinjayYu** [comment]
谢谢分享

**Comment by ly525** [comment]
建议看下@sevencai的建议, 修改下代码吧

**Comment by imsobear** [comment]
@liuyanshi @sevencai 已修正，谢谢反馈。

**Comment by winterJIE** [comment]
搜问题竟然搜到了果大的文章，厉害！

**Comment by Yhspehy** [comment]
@kokokele   
path.dirname()获得的是filename所在文件夹的地址,
所以是path.dirname(_filename) + '/test.js'

**Comment by johnlin0207** [comment]
回头试试再回来赞

**Comment by ghost** [comment]
process.cwd()也比较好理解，表示的是node进程当前所在的路径，因为只有你在一个目录下执行`node *.js`，才会启动一个node进程。所以说，总是返回运行 node 命令时所在的文件夹的绝对路径。`path.resolve`相当于对resolve函数的每一个参数都执行cd命令。例如，path.resolve('./')，而且只有你在一个目录下执行`node ./**/*.js`（执行一系列的cd命令操作，然后运行`node ./**/*.js`），`path.resolve('./')`才可能被执行（`path.resolve('./')`可能存在你执行node操作的js文件中或者存在你执行node操作的js文件且通过require进来的js文件中），这恰恰说明你执行cd操作已经结束啦。所以说`path.resolve('./')`的参考点就是你执行`node ./**/*.js`时的路径

**Comment by SuperAL** [comment]
When using `require`, the path is relative to that source file (**NOT** root directory).
When using `fs`, the path is relative to `process.cwd()` (**NOT** that source file).
[Relative path when using require and fs for node.js](http://samwize.com/2014/02/05/relative-path-when-using-require-and-fs-for-node-dot-js/)

**Comment by liuliangsir** [comment]
@SuperAL 为啥要用英文呢？

**Comment by plh97** [comment]
谢谢，一步一步爬坑中..........

**Comment by mrzxc** [comment]
thanks. let us climb out of the pits. 么么哒

**Comment by jialinhuang00** [comment]
謝謝

**Comment by qiaoqiaowang** [comment]
多谢填坑

**Comment by hollownewman** [comment]
很好的文章，收获多，赞一下。已保存。

**Comment by johnnyZTY** [comment]
thanks

**Comment by lucker-lv** [comment]
thanks

**Comment by wuyaoqing** [comment]
nice 刚刚踩这个坑

**Comment by Liuyll** [comment]
写了两年才偷懒踩坑。。。以前还在骂pysb。。。

**Comment by zhang-glitch** [comment]
一直以为__dirname是执行node命令的路径   感谢

**Comment by qappleh** [comment]
你好 文章可以授权"深圳湾码农"公众号转载吗？会注明作者和原文链接

**Comment by ripperhe** [comment]
感谢 😃

**Comment by tofrankie** [comment]
Mark
