### ISSUE TITLE
some useful git tips for me

### ISSUE THREAD

**Issue by imsobear** [imsobear/blog#56]
关于 git 一些需要记录的东西：
- 在 git 中，默认会忽视文件名大小写的改变，如果需要改文件名的大小写，最佳的方案是修改 git 配置，直接将 `./.git/config` 中的 `ignorecase` 的字段设置为 true 即可。
- 在项目中，使用 git flow 模型是个不错的方案，更妙的是有 [gitflow](https://github.com/nvie/gitflow) 这个工具灰常方便。
- 如何添加空的文件夹，在对应的空文件夹随意添加一个空文件，like .gitkeep
- 一些 git 操作：

``` shell
// 删除远程分支
git push origin --delete <branchName>

// 删除远程 tag
git push origin --delete tag <tagName>

// 推送本地 tag
git push origin <tagName>

// 忽略正在跟踪的文件
git rm --cached <fileName>
```

**Comment by appleboy** [comment]
我個人建議可以參考 [Github Flow](https://guides.github.com/introduction/flow/index.html)

刪除遠端分支也可以透過底下指令:

```
git push origin :branch_name
```

**Comment by imsobear** [comment]
因为仓库是托管在公司内部的 gitlab 上，所以 git flow 更加通用一些。

`git push origin :branch_name` 很赞 :+1: 

and，你是不是用英文重新编辑了 issue，因为在我的 timeline 里显示的是繁体，打开 issue 时却是英文，so strange

**Comment by imsobear** [comment]
@appleboy 

![2015-02-02 2 43 55](https://cloud.githubusercontent.com/assets/2505411/5996816/81133bf4-aaeb-11e4-8e03-d29bf44c22a1.png)

**Comment by appleboy** [comment]
是的，我用英文重新編輯 XD。

公司內部用 gitlab，gitlab 的功能蠻強大的，基本的 github 功能，都可以在 gitlab 上找到，不過流程因人而異，重點是團隊覺得可以就可以。
