### ISSUE TITLE
《批判官员的尺度》

### ISSUE THREAD

**Issue by imsobear** [imsobear/blog#6]
> 若批评不自由，则赞美无意义。

《批判官员的尺度》，先前就知道是一本不错的书，但没想到，我被序言吸引了。被序言吸引的原因有二：一来是译者引起我的好奇心；二来是我把序言看了一半的时候才意识到我看的是序言，而非正文。

本书译者何帆，毕业于武汉大学法学院、中国人民大学法学院，现为最高人民法院法官。坦白来讲，我个人对于体制内的人一直有一种不认可，所以我看了译者的介绍后，心想深入体制的这样一个人，到底能把这本宣扬言论自由的书翻译成什么样子？摘抄序文中的几句话：

当然，美国宪法能够沿用至今，并被誉为“活的宪法”，靠的是最高法院大法官们与时俱进，适时根据社会情势变迁，通过灵活解释，不断赋予宪法条文新的含义。

对言论进行适当限制，当然大有必要，但是，从操作角度看，依法禁止某种言论并不可怕，可怕的是禁止者不给出明确的认定标准，想查禁什么言论，就随意给某种言论贴上禁止“标签”。

看了这些话，改变了我以前那种略有偏激的观点，证明了体制内有很多有想法、有能力、也在不断努力的人，但同时我们必须认识到，有这些人的努力，为什么依然没有突破？或者说中国的宪政历程到底有没有期限？我想，除了那些你我他皆不能左右的原因外，我们每个个体需要不断的去提升自己，胡适之先生有句话说：给你自由，你不独立，仍是奴隶。即便当下的自由不是想象的自由，我们依然可以从独立做起。

好了，这个话题貌似不适合展开下去，先写这么多吧。
## update

前面写过一篇对这本书译者的看法，然后不知道是事太多还是怎么的，花了很久时间才看完这本书。

看的过程，总感觉有一种力量在心底，作者那种对于国家的信任与希冀，以及民众对于公众事件的高参与度皆是我们需要学习的。我们一天总在说着正能量，但心里还是各种负能量，每段时间都要有一些公众事件，不断打破我们好不容易建立起来对于社会主义伟大事业的美好愿望，看不到改变，真的看不到，只学到了新的词语：休假式治疗、轮流发生性关系，又一个中国特色。

这一界领导人上台的时候，看着CCAV新闻对于各种贪污腐败的大力报道，群民齐呼：看来这届领导班子是要狠抓贪腐了！这次我竟然很清醒，事实证明我这次的清醒的确不是装B，不出两月，上天的上天，携夫人出访的也屡试屡爽，永远都是三分钟的热度，撩拨撩拨群民多年压抑的欲望与不满，刚脱下衣服，政府说这次没吃药，下次再来吧。群民本以为久旱逢甘霖，却不料老天爷只是撒泡尿，之后就跟剧本里写的一样了，腐败不反了，CCAV也噤声了，然后民众继续积累压抑以供下一届继续撩拨。

说一切都在变好，我总感觉一切都在走下坡路，经济、就业、90后的价值观走向，更勿须提什么民主与自由，这词语创造出来就是立牌坊的。

摘抄书中的几句话：
1. 联邦主义，是美国政治权力架构的基本原则，决定了联邦政府与各州政府的权力划分。
2. 联邦制度的一大优点在于，只要得到选民支持，任何一个州都可以成为实验室，尝试各种新兴的社会与经济实验，却不会对国家造成任何危险。
3. 自由很重要，但新闻工作者更应该具有责任感。
4. 知识将永远统治愚昧：人民若想当家做主，必须用知识的力量武装自己。
5. 政府必须容忍一个不断找茬的新闻界，一个顽固倔强的新闻界，一个无处不在的新闻界？
6. 如果我们想确定一种思想是否真理，就应让它在思想市场的竞争中接受检验。
7. 自由的最大威胁，是思维僵化、消极冷漠的民众。
8. 言论的一大职能，就是将人们从非理性恐惧的桎。中解脱出来。
9. 那些通过革命，为我们争得独立者并非懦夫。他们不是畏惧政治改革。他们不会仅为维持秩序，就牺牲人民的自由。
10. 如果有检查言论的权力，那也应当是人民检查政府的权力，而不是政府检查人民的言论。
11. 然而，宪法的生命力之所以能恒久延续，源自法官们在适用与解释上的不断创新，以适应制宪先贤们未能预测到的社会变迁。

愿一切真能变好！

**Comment by johnwatsondev** [comment]
我发现程序员关心政治的还是蛮多的，请问阁下关注过 “编程随想” 嘛？:P

**Comment by imsobear** [comment]
@johnwatsondev 哈，年幼无知时喜欢关心政治问题，离开学校工作之后貌似也不怎么关心了。编程随想大概有了解过，没有认真读过吧。
